version: "3.10"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/
    ports:
      - "5432:5432"


  calendar_app:
    links:
      - postgres
    build: ./calendar_app
    command: uvicorn main:calendar_app --host 0.0.0.0 --port 9000
    ports:
      - "9000:9000"

  user_app:
    links:
      - postgres
    build: ./user_app
    command: uvicorn main:user_system --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"


volumes:
  pgdata: