version: "3.10"

services:


  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/
    ports:
      - "5432:5432"


  rabbitmq:
    image: rabbitmq:3.10.7-management
#    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672


  calendar_app:
    links:
      - postgres
    build: ./calendar_app
    command: uvicorn main:calendar_app --host 0.0.0.0 --port 9000
    ports:
      - "9000:9000"


  user_app:
    links:
      - postgres
      - rabbitmq
    build: ./user_app
    command: uvicorn main:user_system --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"


  cart_app:
    links:
      - postgres
    build: ./cart_app
    command: uvicorn main:cart_system --host 0.0.0.0 --port 7000
    ports:
      - "7000:7000"


volumes:
  pgdata:
